services:
  app:
    container_name: laravel-template-app
    build: ./docker/app
    volumes:
      - ./:/var/www/html

  nginx:
    container_name: laravel-template-nginx
    build: ./docker/nginx
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./:/var/www/html
  
  mysql:
    container_name: laravel_template-mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/msql/conf.d
    environment:
      MYSQL_DATABASE: laravel_template
      MYSQL_USER: laravel_template
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'